### ISSUE TITLE
'Wildcards' object has no attribute 'memory'

### ISSUE THREAD

**Issue by cassondranewman** [a-ludi/dentist#10]
Hello, 

I have been attempting to get dentist to complete on a cluster managed by slurm. Dentist fails with this message: 
```
WorkflowError in line 562 of /lustre/project/gbru/gbru_X/RawData/dentist/Snakefile:
'Wildcards' object has no attribute 'memory'
  File "/software/7/apps/snakemake/5.25.0/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 111, in run_jobs
  File "/software/7/apps/snakemake/5.25.0/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 920, in run
```
I am worried that dentist/snakemake is not "seeing" the cluster.yml file which lists memory for the workflow. How can I fix this so that I can run dentist to completion? 

My stderr, script, config.yaml, cluster.yml and snakemake.yml files are attached. 
[stderr.txt](https://github.com/a-ludi/dentist/files/5441874/stderr.txt)
[Dentist_Script.txt](https://github.com/a-ludi/dentist/files/5441883/Dentist_Script.txt)
[config.yaml.txt](https://github.com/a-ludi/dentist/files/5441884/config.yaml.txt)
[cluster.txt](https://github.com/a-ludi/dentist/files/5441887/cluster.txt)
[snakemake.txt](https://github.com/a-ludi/dentist/files/5441935/snakemake.txt)

**Comment by a-ludi** [comment]
Generally speaking, this error occurs usually if Snakemake attempts to execute a rule on the cluster for which there is no proper entry in `cluster.yml`. The violating rule is the last one listed in the Snakemake log, in this example it is `mask_tandem`. A direct fix for the issue is to insert an appropriate section into `cluster.yml`, e.g.:

```yaml
mask_tandem:
    memory:     8192
    time:       "00:30"
```

---

That said, it seems your specific problem occurred because the `Snakefile` and `cluster.yml` are out of sync (`Snakefile` is older than the `cluster.yml`). Please make sure you are using `dentist`, `Snakefile` and `cluster.yml` from the same git commit. If the issue persists, please report back and will fix the `cluster.yml` in the repo.

**Comment by cassondranewman** [comment]
Thank you for looking into this! I truly appreciate it. 

I began looking through each file to make sure it matched the example provided by dentist/1.0.0-beta.3. Before rerunning the entire pipeline, I tried these commands:

```
snakemake --profile /home/cassie.newman/.config/snakemake/snakemake_profile/
snakemake --profile snakemake_profile

```
which both returned the error: 

```
KeyError in line 373 of /lustre/project/gbru/gbru_peanut2/RawData/dentist/Snakefile:
'inputs'
  File "/lustre/project/gbru/gbru_peanut2/RawData/dentist/Snakefile", line 373, in <module>
```

Which again leads me to believe that snakemake is not able to communicate/read my input files. Is there something I am grossly overlooking? 

Once I figure out this error, I will try to rerun the entire pipeline.

**Comment by cassondranewman** [comment]
After working with my cluster admin and adding more sections to the cluster.yml, the job was able to complete. Thank you for your help.
