### ISSUE TITLE
DALIGNER version

### ISSUE THREAD

**Issue by EdHarry** [a-ludi/dentist#14]
Hi,

I'm getting a lot of `LAcheck` errors when I try running dentist (via singularity).

Your `Snakefile` reports the following message in the logs 
```
Duplicate LAs: can be fixed by LAsort from 2020-03-22 or later.
```
But your dependencies section in the README has `DALIGNER (=2020-01-15)` i.e. git brach `c2b47da6b3c94ed248a6be395c5b96a4e63b3f63` (which is used in your docker recipe)

Is dentist tied to DALIGNER version 2020-01-15 or can the bug-fixed version from 2020-03-22 be used?

**Comment by a-ludi** [comment]
Hi,

the quick solution is simple: just issue `export SKIP_LACHECK=1` before running Snakemake. If there are only "duplicate LAs" this will produce entirely correct results. As I have never seen any other error, this is pretty safe.

DENTIST is not itself tied to any specific `daligner` version but `damapper` is because it calls some of the auxiliary tools like `LAsort` and `LAmerge`. The versions specified in the README (and used in the container) are the most recent working combination.

**Comment by EdHarry** [comment]
Ok, I'll try disabling the LAchecks.

I'm assuming that any other errors that LAcheck would potentially catch
would cause further downstream errors?

**Comment by a-ludi** [comment]
> I'm assuming that any other errors that LAcheck would potentially catch would cause further downstream errors?

I am afraid there is no guarantee for that in the optimized binaries included in the container. However, it is unlikely that there is any other error. You can check the corresponding log files `logs/*alignment*.log` for other errors if you like but `LAcheck` just stops after the issue so there is still a chance something went wrong.

I am sorry for this inconvenience. Actually, I asked the author of these tools to include the removal of duplicate LAs into `LAsort` which is mentioned in the message but as I explained the version became incompatible for other reasons. I really hope I can depart from `damapper` sometime in the future but for now it is the best option.

**Comment by EdHarry** [comment]
No problem, thanks for letting me know.
