### ISSUE TITLE
Syntax issue in snakemake

### ISSUE THREAD

**Issue by harish0201** [a-ludi/dentist#4]
Hi, 

Apologies that I'm pasting screenshots here, in unable to login through my workstation.

The following are the versions that I'm using:
Snakemake: 3.13.3
dentist v1.0.0-beta.1 (commit 9e049a98751bee89de49546e1138c18f009a77fe)

Issue:

![image](https://user-images.githubusercontent.com/9093815/82551305-77a14200-9b4f-11ea-8a83-02aeca79e9e0.png)

The second is the location of the same with respect to the Snakemake file:
![1590057598372_image](https://user-images.githubusercontent.com/9093815/82551353-8c7dd580-9b4f-11ea-9491-b401a2952124.png)

I'd appreciate any help regarding the same

**Comment by a-ludi** [comment]
Hi, you will need to use a newer version of snakemake. I recommend at least >=5.10.0. Best use the latest version as of now.

**Comment by harish0201** [comment]
Hi, thanks for the suggestion. I have installed snakemake from bioconda and the version is 5.3.0

The error remains the same.

**Comment by a-ludi** [comment]
The reason that you get the syntax error is that your version of snakemake does not know about `checkpoint`s. The feature has been [introduced in version 5.4.0](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id80).

So, your version is still not recent enough. There are [newer versions available](https://bioconda.github.io/recipes/snakemake/README.html?highlight=snakemake#recipe-Recipe%20&#x27;snakemake&#x27;) on biocaonda, so please update using `conda update snakemake`.

Note: I recommend a version >=5.10.0 because I encountered several bugs in the checkpoints feature in older versions. I am using 5.10.0 right now and there are no issues anymore.
